export const BlogPage = () => {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur aspernatur delectus accusantium repudiandae. Blanditiis, iste adipisci debitis quam obcaecati reprehenderit, est incidunt unde eaque, dolores cupiditate ad. Nesciunt praesentium iusto nulla dolore qui quis, incidunt laborum? Unde laudantium placeat perferendis itaque, aliquid a magnam quis quo quas aspernatur sint voluptas! Voluptatem doloribus magni dignissimos quia voluptate maiores inventore numquam, itaque alias error laudantium, incidunt commodi, facere blanditiis qui. Vero magnam sed eveniet odio mollitia atque recusandae suscipit quis quibusdam quam autem deserunt natus odit, ullam rerum doloremque ipsa nemo laborum laudantium cum aliquam tenetur quas impedit? Repudiandae enim minima omnis!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur aspernatur delectus accusantium repudiandae. Blanditiis, iste adipisci debitis quam obcaecati reprehenderit, est incidunt unde eaque, dolores cupiditate ad. Nesciunt praesentium iusto nulla dolore qui quis, incidunt laborum? Unde laudantium placeat perferendis itaque, aliquid a magnam quis quo quas aspernatur sint voluptas! Voluptatem doloribus magni dignissimos quia voluptate maiores inventore numquam, itaque alias error laudantium, incidunt commodi, facere blanditiis qui. Vero magnam sed eveniet odio mollitia atque recusandae suscipit quis quibusdam quam autem deserunt natus odit, ullam rerum doloremque ipsa nemo laborum laudantium cum aliquam tenetur quas impedit? Repudiandae enim minima omnis!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur aspernatur delectus accusantium repudiandae. Blanditiis, iste adipisci debitis quam obcaecati reprehenderit, est incidunt unde eaque, dolores cupiditate ad. Nesciunt praesentium iusto nulla dolore qui quis, incidunt laborum? Unde laudantium placeat perferendis itaque, aliquid a magnam quis quo quas aspernatur sint voluptas! Voluptatem doloribus magni dignissimos quia voluptate maiores inventore numquam, itaque alias error laudantium, incidunt commodi, facere blanditiis qui. Vero magnam sed eveniet odio mollitia atque recusandae suscipit quis quibusdam quam autem deserunt natus odit, ullam rerum doloremque ipsa nemo laborum laudantium cum aliquam tenetur quas impedit? Repudiandae enim minima omnis!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur aspernatur delectus accusantium repudiandae. Blanditiis, iste adipisci debitis quam obcaecati reprehenderit, est incidunt unde eaque, dolores cupiditate ad. Nesciunt praesentium iusto nulla dolore qui quis, incidunt laborum? Unde laudantium placeat perferendis itaque, aliquid a magnam quis quo quas aspernatur sint voluptas! Voluptatem doloribus magni dignissimos quia voluptate maiores inventore numquam, itaque alias error laudantium, incidunt commodi, facere blanditiis qui. Vero magnam sed eveniet odio mollitia atque recusandae suscipit quis quibusdam quam autem deserunt natus odit, ullam rerum doloremque ipsa nemo laborum laudantium cum aliquam tenetur quas impedit? Repudiandae enim minima omnis!</p>
    </div>
  );
};
